ignore:
  - vulnerability: GHSA-34x7-hfp2-rc4v
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-3966-f6p6-2qr9
  - vulnerability: GHSA-8qq5-rm4j-mr97

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
