instrumentation:
  include-all-sources: true
  excludes: [
    '**/test/**,
    src/models/index.js'
  ]
check:
  global:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
  each:
    statements: 90
    lines: 90
    branches: 90
    functions: 90
