## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  # @hapi/catbox-memory v6 and onwards breaks tests. Needs investigation.
  "@hapi/catbox-memory",
  # running stable versions until lag issue is fixed
  "@mojaloop/central-ledger",
  "@mojaloop/central-services-shared",
  "@mojaloop/central-services-stream",
  # upgrading @mojaloop/central-services-error-handling beyond v12.0.7 causes peer dependencies conflict.
  # can be upgraded when @mojaloop/central-services-health and @mojaloop/sdk-standard-components are upgraded.
  "@mojaloop/central-services-error-handling",
  "@mojaloop/event-sdk",
  # prevents CI from running package install in v6.1.1
  "sinon",
  "node-fetch"
]
