## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  # @hapi/catbox-memory v6 and onwards breaks tests. Needs investigation.
  "@hapi/catbox-memory",
  # @mojaloop/central-services-shared v18.5.0 and onwards breaks tests. Needs investigation.
  "@mojaloop/central-services-shared",
#  # running stable versions until lag issue is fixed
#  "@mojaloop/central-ledger",
#  "@mojaloop/central-services-shared",
#  "@mojaloop/central-services-stream",
#  "@mojaloop/event-sdk",
#  # prevents CI from running package install in v6.1.1
#  "sinon"
]
