temp-directory: "./.nyc_output"
check-coverage: true
per-file: true
lines: 90
statements: 90
functions: 90
branches: 90
all: true
include: [
  "src/**/*.js"
]
instrument: true
reporter: [
  "lcov",
  "text-summary",
  "html"
]
exclude: [
  "**/node_modules/**",
  '**/migrations/**',
  '**/docs/**',
  'src/models/settlementWindow/facade.js' # TODO: remove this line once test coverage is updated  
]
